Adding subscription_id and stream_response_time_ns to subscribe response metadata [ --feature stats ]
eclipse-kuksa/kuksa-databroker pull request #32
Opened 2024-05-14 09:11 UTC by LikhithST

Adding metadata related to "time to process requests" for set and subscribe calls, adding under the feature stats

2024-05-14 10:13 UTC, erikbosch commented on databroker/src/broker.rs
> +#[cfg(not(feature="stats"))]
If intended for main branch, should we possibly somewhere document what the feature "stats" is intended for and how it works.

2024-05-14 10:27 UTC, argerus requested changes
So first of all, this change is way too intrusive for what I'm guessing is the intended purpose, so a short description of what the PR intends to accomplish would be good.

Secondly, if the intent is to collect metrics from a running databroker instance, have you looked into using the [`tracing`](https://docs.rs/tracing/latest/tracing/) library (which databroker already uses for logging) in order to collect these things and wire it up to open telemetry or something in order to subscribe to it?

2024-06-13 10:48 UTC, erikbosch commented on data/vss-core/vss_release_4.0.json
> +{ "Vehicle": { "children": { "ADAS": { "children": { "ABS": { "children": { "IsEnabled": { "datatype": "boolean", "description": "Indicates if ABS is enabled. True = Enabled. False = Disabled.", "typ
What changes have you done here?

2024-06-13 10:51 UTC, erikbosch commented on dockerfile
> +# Use the latest version of the Rust base image
I find a bit confusing to have one dockerfile here and others in https://github.com/eclipse-kuksa/kuksa-databroker/blob/main/scripts/Dockerfile

What is the difference between them. Should better be described somewhere.

2024-06-13 10:55 UTC, erikbosch commented on Latency_Extractor_ReadMe.md
> +By following these steps, you will be able to build and run the Kuksa Data Broker with the stats feature enabled. If you encounter any issues or have further questions, please refer to the official d
If we are to add a stats feature we should better have a better description on what it does. Like what stats does it collect and how can you review them. I would suggest adding some screenshots - it seems that we start a grafan instance, what would you be able to see there and so on.

2024-06-13 10:56 UTC, erikbosch commented on Latency_Extractor_ReadMe.md
> +# Kuksa Data Broker
If we are to merge this PR I would like a link from the main README to this file

2024-06-13 10:57 UTC, erikbosch commented
There are conflicts that needs to be fixed

2024-06-13 12:02 UTC, lukasmittag commented
Hey @LikhithST, for now I'm closing this. As discussed we will work on a fork on this. We then can decide to open a PR with some things that we also want here. @erikbosch thanks for taking a look, without context this PR can be confusing. @LikhithST thanks for the work you have done so far.

2024-06-13 12:02 UTC, closed without merging